
'use client';

import { useEffect } from 'react';
import { useRouter } from 'next/navigation';
import { useFirestore, useUser, addDocumentNonBlocking } from '@/firebase';
import { collection, serverTimestamp } from 'firebase/firestore';
import type { AiBook } from '@/lib/types';
import { LoaderCircle } from 'lucide-react';
import { placeholderBookData } from '@/lib/placeholder-data';


export default function NewBookPage() {
  const firestore = useFirestore();
  const { user, isUserLoading } = useUser();
  const router = useRouter();

  useEffect(() => {
    if (isUserLoading) {
      // Wait until user status is resolved
      return;
    }

    if (!user) {
      // If no user, redirect to home page to login
      router.replace('/');
      return;
    }

    // Once user is confirmed, create the new book
    const createNewBook = async () => {
      // Using placeholder data as a template for a new book
      const newBookData: Omit<AiBook, 'id'> = {
        ...placeholderBookData,
        id: '', // id will be generated by firestore
        ownerId: user.uid,
        name: 'Nova Coleção (Copie e Edite)',
        shortDescription: 'Comece com este modelo e personalize sua nova coleção de tatuagens.',
        // createdAt: serverTimestamp(), // Optional: for sorting
      };
      // remove id from newBookData
      delete (newBookData as Partial<AiBook>).id;


      try {
        const booksCollection = collection(firestore, 'ai_books');
        const docRef = await addDocumentNonBlocking(booksCollection, newBookData);
        
        if (docRef) {
          router.replace(`/books/${docRef.id}`);
        } else {
            // Handle case where docRef is not returned, maybe show an error
            router.replace('/');
        }
      } catch (error) {
        console.error('Error creating new book:', error);
        // Optionally, show a toast notification to the user
        router.replace('/');
      }
    };

    createNewBook();
  }, [user, isUserLoading, firestore, router]);

  return (
    <div className="flex h-screen w-full flex-col items-center justify-center gap-4 bg-background">
      <LoaderCircle className="h-8 w-8 animate-spin text-primary" />
      <h1 className="font-semibold text-2xl">Criando sua nova coleção...</h1>
      <p className="text-muted-foreground">Aguarde, estamos preparando tudo para você.</p>
    </div>
  );
}
